import { Sidebar } from "./admin/components/sidebar"
import "../(front)/globals.css"
import { AdminNavbar } from "./admin/components/admin-navbar"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <div className="flex flex-1 flex-col gap-2">
       <AdminNavbar/>
       <div className="flex flex-1">
        <div className="w-3/12">
        <Sidebar/></div>
        <div className="w-9/12">
        <div className="p-5">{children}</div> 

        </div>
       </div>

       </div>

        
       </body>
    </html>
  )
}
